export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const FETCH_ARTICLES_BY_TOPIC_REQUEST = 'FETCH_ARTICLES_BY_TOPIC_REQUEST';
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS = 'FETCH_ARTICLES_BY_TOPIC_SUCCESS';
export const FETCH_ARTICLES_BY_TOPIC_FAILURE = 'FETCH_ARTICLES_BY_TOPIC_FAILURE';

export const FETCH_COMMENTS_BY_ARTICLE_REQUEST = 'FETCH_COMMENTS_BY_ARTICLE_REQUEST';
export const FETCH_COMMENTS_BY_ARTICLE_SUCCESS = 'FETCH_COMMENTS_BY_ARTICLE_SUCCESS';
export const FETCH_COMMENTS_BY_ARTICLE_FAILURE = 'FETCH_COMMENTS_BY_ARTICLE_FAILURE';

export const POST_NEW_COMMENT_REQUEST = 'POST_NEW_COMMENT_REQUEST';
export const POST_NEW_COMMENT_SUCCESS = 'POST_NEW_COMMENT_SUCCESS';
export const POST_NEW_COMMENT_FAILURE = 'POST_NEW_COMMENT_FAILURE';

export const ALTER_ARTICLE_VOTE_REQUEST = 'ALTER_ARTICLE_VOTE_REQUEST';
export const ALTER_ARTICLE_VOTE_SUCCESS = 'ALTER_ARTICLE_VOTE_SUCCESS';
export const ALTER_ARTICLE_VOTE_FAILURE = 'ALTER_ARTICLE_VOTE_FAILURE';
